### ISSUE TITLE
serokell-util import is redundant

### ISSUE THREAD

**Issue by volhovm** [serokell/log-warper#2]
Log-warper itself is a relatively small and convenient wrapper over `hslogger`. It imports `serokell-util` though. The only usage is here:
```
ξ> grep -R "Serokell.Util." src/
src/System/Wlog/LoggerNameBox.hs:import           Serokell.Util.Lens          (WrappedM (..))
```
Which defines the only instance:
```
instance Monad m => WrappedM (LoggerNameBox m) where
    type UnwrappedM (LoggerNameBox m) = ReaderT LoggerName m
    _WrappedM = iso loggerNameBoxEntry LoggerNameBox
```
The cons of importing `serokell-util` are:
* Requires far more dependencies to be downloaded (>15 or something)
* Requires files from non-lts to be manually added to `stack.yaml`
* Well, it's counterintuitive. Most projects that use `log-warper` most likely don't want `serokell-util` to be in dependencies.

I suggest to either:
* Import `log-warper` in `serokell-util` and place this instance near `WrappedM` declaration.
* Place this instance in real projects that we use both libraries in.

cc @ChShersh

**Comment by chshersh** [comment]
I agree with the fact that we can move `WrappedM` instance from `log-warper` library into `serokell-util`. But there is very big chance we will use `serokell-util` in the future inside `log-warper` when library become mature. It make more sense for me to review instead `serokell-util` library to make it smaller, remove some outdated functions and dependencies from there, maybe move something into separate project.

**Comment by chshersh** [comment]
Issue is done under this commit: https://github.com/serokell/log-warper/commit/6ef6f2df1fa311c7cef47f9127e6aef71c4b1022

**Comment by volhovm** [comment]
Please bump the version also.
