### ISSUE TITLE
Add function that will deal with `forkIO`-like functions

### ISSUE THREAD

**Issue by vrom911** [serokell/log-warper#50]
As it was very often pattern I've implemented 
```
forkLogIO :: (MonadIO m, WithLogger m) => LoggerNameBox IO () -> m ThreadId
forkLogIO action = do
    logName <- askLoggerName
    liftIO $ forkIO $ usingLoggerName logName $ action
```
It would be helpful to have something more common not related only to `forkIO`.

**Comment by chshersh** [comment]
@vrom911 This might be helpful! Especially with proper documentation and examples.
