### ISSUE TITLE
Example '.yaml' is broken

### ISSUE THREAD

**Issue by chshersh** [serokell/log-warper#64]
Example logger config is broken. Here I see `severity` on top-level. But this field is never used.

https://github.com/serokell/log-warper/blob/f93fe3bbe54314c088fe32dfc1cbca93735f7661/logger-config-example.yaml#L4

This should be severity for root logger and it should be moved into `loggerTree:`. Also this should be tested inside `Playground.hs`.

**Comment by vrom911** [comment]
@ChShersh , Probably we need some tests on that, so it won't broke after any changes in `log-warper`?

**Comment by chshersh** [comment]
@vrom911 Well, it's far from obvious to me how we can test `log-warper`... There exist related issue #22.
But testing system implementation will require some significant amount of time... I agree that we should have it. But it just not too easy to implement...

For now, what I want from this issue:
1. Move top-level `severity: Warning+` to `logTree`.
2. Remove pure logging example from `Playground` (there's no need in this because we will have pure logging tutorial).
3. Add two additional log-messages to `log-warper` with some not-configured name: `Debug` and `Warning`.

So the expecting behavior is that we will see `Warning` message from this logger but won't see `Debug` message.
