### ISSUE TITLE
Optimize 'log-warper' dependencies

### ISSUE THREAD

**Issue by chshersh** [serokell/log-warper#71]
`log-warper` has a lot of dependencies. Probably some of them can be removed or replaced...

- [x] `lens` replaced with `microlens`-family.
- [x] `dlist` removed (`DList` replaced with `Seq` from `containers` package).
- [x] `extra` maybe can be removed (I guess we have everything in `universum`?)
- [x] `errors` package can be removed (it's used only for one operator or something like that)
- [x] `exceptions` package can be removed (we use `safe-exceptions` in `universum`)
- [x] `hashable` can be removed from `cabal` file (we have it in `universum`)
- [x] `network` — why we need `network` in logging package?
- [x] `text-format` is probably not needed
- [x] ~~`transformers-base` is probably not needed~~
- [x] Bump up to `universum-0.9.1`
- [x] Bump up to `universum-1.0.0`
- [x] `formatting` package can be removed (we use `fmt` and `fmt` should be preferred to `formatting`)

Dependencies should be optimized in every target.

**Comment by chshersh** [comment]
Just some numbers for further consideration:

```bash
$ stack list-dependencies | wc -l
89
$ stack list-dependencies --test | wc -l
104
```

**Comment by vrom911** [comment]
For the moment there are both `fmt` and `formatting` libraries. Can we get rid of `formatting`?

**Comment by chshersh** [comment]
@vrom911 Yes, I think we can get rid of `formatting` library. This will be a good change! I've updated issue description.
