### ISSUE TITLE
Make it possible to change configuration dynamically

### ISSUE THREAD

**Issue by gromakovsky** [serokell/log-warper#94]
As I was told, currently configuration is static and can't be changed during process running. But sometimes it's convenient to be able to change it.
My use case is that I want to temporarily disable terminal logging.
It would be good to have a convenient way to do it.
IIRC, `hslogger` provided such ability.
It's not a priority for me, I will find another solution in my use case (I already have it in mind), but I think it's a useful feature anyway.

**Comment by chshersh** [comment]
> IIRC, hslogger provided such ability.

Well, strictly speaking, `log-warper` also has such ability. It just requires to use unpleasant low-level interface. It requires other features to be implemented first, like, moving configuration inside `ReaderT` context:

- [ ] #47: Move `LogInternalState` from global mutable variable to `ReaderT`
- [ ] #95: Move `LoggerConfig` into `ReaderT`

**Comment by chshersh** [comment]
Done in 2.0.
